# Generated by Django 5.2.7 on 2025-11-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('province', models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('KPK', 'KPK'), ('Balochistan', 'Balochistan')], max_length=50)),
                ('category', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable')], max_length=50)),
            ],
        ),
    ]
